name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

# Explicitly grant write access to repository contents
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          # Necessary if you want to push changes back to the branch
          ref: ${{ github.head_ref }}

      - name: Set up JDK 25
        uses: actions/setup-java@v4
        with:
          java-version: '25'
          distribution: 'temurin'
          cache: maven

      - name: Check and Fix formatting
        uses: axel-op/googlejavaformat-action@v3
        with:
          args: "--replace"
          # This action usually requires a commit-message to actually push the changes
          commit-message: "style: auto-format Java code"

      - name: Build and Test with Maven
        run: mvn -B package --file pom.xml